---
title: "Learn quillt"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Learn quillt}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

**quillt** is a template pkgdown package for the R Markdown Ecosystem. To learn more about
template for pkgdown website see https://pkgdown.r-lib.org/reference/build_site.html#yaml-config-template

This template contains a theme and some assets dedicated to be used by R Markdown related pkgdown website. This vignettes aim to explain how to setup a new website using **quillt**

## How-to

**quillt** contains some usethis-like helper functions to quickly and easily setup a new website with the shared components and assets. This can also be used with existing website to migrate to quillt but you'll need to carefully look through the git diff.

* ` quillt::use_quillt_pkgdown()` is the main function that will set everything up. 

* `quillt::use_github_action_quillt_pkgdown()` is the companion function to setup a Github Action to deploy to website to netlify 

## Specification of a quillt website

* Uses the theme provided by **quillt**
* Contains `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md`
* pkgdown website must share the same navbar configured in the template, i.e :
    * Get Started
    * Examples
    * Articles
    * References
    * News
    * Github Icon
* `README.md` is used for homepage which contains at least the same header in order:
    * Package Name + icon, then short description
    * Featured documentation (like books, cheatsheets, ...)
    * Installation steps (CRAN + Github)
    * Usage (Quick intro)
    * Getting help (link to Q&A website like RStudio Community or StackOverflow)
    * Code Of Conduct (linking to the COC page)
* Some component should not be change
    * Footer message
    * No additional navbar menu
    * Homepage header with icon
    * No other icon in navbar - Github should be the only one on the far right.
    
Aim is that a common look and feel is shared accross related packages.

#### Testing h4 headers

